spring.application.name=backend
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
azure.speech.key=${AZURE_SPEECH_KEY}
azure.speech.region=${AZURE_SPEECH_REGION}